version: "3.8"

services:
  airway_reservation:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./containers/airway_reservation/Dockerfile
    ports:
      - 8088:8088
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - airway_reservation
    image: airway_reservation-app
  postgres:
    image: postgis/postgis:15-3.4
    platform: linux/amd64
    hostname: postgres
    container_name: aw-postgres
    ports:
      - 5432:5432
    networks:
      - airway_reservation
    env_file:
      - .env
    restart: always

networks:
  airway_reservation:
