openapi: 3.0.3
info:
  title: ドローン航路API（A-1-3）
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  description:
security:
  - ApiKeyAuth: []

paths:
  /airwayReservations:
    post:
      tags:
        - 航路予約サービス
      summary: 航路予約API
      operationId: reserveAirway
      description: >-
        運航事業者が航路を予約するため、予約したい航路区画毎に利用したい日時を指定して航路予約を申請、予約結果を返却する。<br/>
        航路予約情報は、航路区画IDおよびそれに紐づく予約時間範囲、予約した運航事業者IDと予約ID、予約ステータス、予約完了日時で構成される想定。<br/>
        新規予約時は予約状態更新日時は空となる。<br/>
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReserveAirwayRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirwayReservationResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400Response'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404Response'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500Response'
  /operator/{operatorId}/airwayReservations:
    get:
      tags:
        - 航路予約サービス
      summary: 航路予約一覧取得API（運航事業者向け）
      operationId: listAirwayReservationByOperator
      description: >-
        運航事業者が自身の航路予約一覧を確認するため、予約一覧を確認すると、要求した運航事業者の航路予約情報返却する。<br/>
        航路予約情報は、航路区画IDおよびそれに紐づく予約時間範囲、予約した運航事業者IDと予約ID、予約ステータス、予約完了日時、そして予約状態更新日時で構成される想定。<br/>
        予約終了時刻を過ぎたものはデフォルトでは返さない、返したい場合はフラグ制御してもいいが大量データの場合は厳しいので必要に応じて別APIとして切り出す。<br/>
      parameters:
        - name: operatorId
          required: true
          in: path
          schema:
            type: string
            format: uuid
            minLength: 36
            maxLength: 36
            description: 運航事業者ID
            example: '123e4567-e89b-12d3-a456-426614174000'
        - name: page
          required: false
          in: query
          schema:
            type: integer
            default: 1
            maximum: 9999
            description: ページ番号
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirwayReservationsResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400Response'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404Response'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500Response'
  /admin/airwayReservations:
    get:
      tags:
        - 航路予約サービス
      summary: 航路予約一覧取得API（航路運営者向け）
      operationId: listAirwayReservationByAdministrator
      description: >-
        航路運営者が自身の運営している航路予約一覧を確認するため、予約一覧を確認すると、要求した運営している航路の航路予約情報を返却する。<br/>
        航路予約情報は、航路区画IDおよびそれに紐づく予約時間範囲、予約した運航事業者IDと予約ID、予約ステータス、予約完了日時、そして予約状態更新日時で構成される想定。<br/>
        予約終了時刻を過ぎたものはデフォルトでは返さない、返したい場合はフラグ制御してもいいが大量データの場合は厳しいので必要に応じて別APIとして切り出す。<br/>
      parameters:
        - name: page
          required: false
          in: query
          schema:
            type: integer
            default: 1
            maximum: 9999
            description: ページ番号
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirwayReservationsResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400Response'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404Response'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500Response'
  /airwayReservations/{airwayReservationId}:
    get:
      tags:
        - 航路予約サービス
      summary: 航路予約詳細取得API
      operationId: getAirwayReservation
      description: >-
        航路予約IDをキーに航路予約の詳細情報を取得する
      parameters:
        - name: airwayReservationId
          required: true
          in: path
          schema:
            type: string
            format: uuid
            minLength: 36
            maxLength: 36
            description: 航路予約ID
            example: '123e4567-e89b-12d3-a456-426614174000'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirwayReservationResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400Response'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404Response'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500Response'
  /airwayReservations/{airwayReservationId}/cancel:
    put:
      tags:
        - 航路予約サービス
      summary: 航路予約取消API（運航事業者向け）
      operationId: cancelAirwayReservation
      description: >-
        運航事業者が自身が予約した航路予約をキャンセルするため、キャンセルしたい予約IDで航路予約取消要求をおこない、キャンセル結果を返却する。
      parameters:
        - name: airwayReservationId
          required: true
          in: path
          schema:
            type: string
            format: uuid
            minLength: 36
            maxLength: 36
            description: 航路予約ID
            example: '123e4567-e89b-12d3-a456-426614174000'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirwayReservationCancellationResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400Response'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404Response'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500Response'
  /admin/airwayReservations/{airwayReservationId}/rescind:
    put:
      tags:
        - 航路予約サービス
      summary: 航路予約撤回API（航路運営者向け）
      operationId: rescindAirwayReservation
      description: >-
        航路運営者が航路事業者が予約した航路予約を撤回するため、撤回したい予約IDで航路予約撤回要求をおこない、撤回結果を返却する。
      parameters:
        - name: airwayReservationId
          required: true
          in: path
          schema:
            type: string
            format: uuid
            minLength: 36
            maxLength: 36
            description: 航路予約ID
            example: '123e4567-e89b-12d3-a456-426614174000'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirwayReservationRescissionResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400Response'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404Response'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500Response'
components:
  securitySchemes:
    ApiKeyAuth:
      description: A-1-3のAPI Gatewayにて生成されたキー。MVP3ではデプロイ先の共通API Gatewayで認証するため削除予定。
      type: apiKey
      name: Authorization
      in: header
  schemas:
    ReserveAirwayRequest:
      type: object
      required:
        - operatorId
        - airwaySections
        - startAt
        - endAt
      properties:
        operatorId:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: 運航事業者ID
          example: '123e4567-e89b-12d3-a456-426614174000'
        airwaySections:
          type: array
          minItems: 1
          maxItems: 99
          description: 航路区画配列
          items:
            type: object
            required:
              - airwaySectionId
              - startAt
              - endAt
            properties:
              airwaySectionId:
                type: string
                format: uuid
                minLength: 36
                maxLength: 36
                description: 航路区画ID
                example: '123e4567-e89b-12d3-a456-426614174000'
              startAt:
                type: string
                format: date-time
                description: 航路区画毎の予約開始日時
                example: '2025-01-13T09:00:00Z'
              endAt:
                type: string
                format: date-time
                description: 航路区画毎の予約終了日時
                example: '2025-01-13T16:00:00Z'
    AirwayReservationResponse:
      type: object
      required:
        - airwayReservationId
        - operatorId
        - airwaySections
        - startAt
        - endAt
        - reservedAt
        - updatedAt
      properties:
        airwayReservationId:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: 航路予約ID
          example: '123e4567-e89b-12d3-a456-426614174000'
        operatorId:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: 運航事業者ID
          example: '123e4567-e89b-12d3-a456-426614174000'
        airwaySections:
          type: array
          minItems: 1
          maxItems: 99
          description: 航路区画予約情報
          items:
            type: object
            required:
              - airwaySectionId
              - startAt
              - endAt
            properties:
              airwaySectionId:
                type: string
                format: uuid
                minLength: 36
                maxLength: 36
                description: 航路区画ID
                example: '123e4567-e89b-12d3-a456-426614174000'
              startAt:
                type: string
                format: date-time
                description: 航路区画毎の予約開始日時
                example: '2025-01-13T09:00:00Z'
              endAt:
                type: string
                format: date-time
                description: 航路区画毎の予約終了日時
                example: '2025-01-13T16:00:00Z'
        status:
          type: string
          enum:
            - 'RESERVED'
            - 'CANCELED'
            - 'RESCINDED'
          description: 予約ステータス
          example: 'RESERVED'
        reservedAt:
          type: string
          format: date-time
          description: 予約完了日時
          example: '2024-12-13T18:53:38Z'
        updatedAt:
          type: string
          format: date-time
          description: 予約状態更新日時（登録時も更新）
          example: '2024-12-13T18:53:38Z'
    AirwayReservationsResponse:
      type: object
      properties:
        result:
          type: array
          items:
            $ref: '#/components/schemas/AirwayReservationResponse'
        total:
          type: integer
          default: 1
          maximum: 9999
          description: 総項目数
        currentPage:
          type: integer
          default: 1
          maximum: 9999
          description: 現在ページ番号
        lastPage:
          type: integer
          default: 1
          maximum: 9999
          description: 最終ページ番号
        perPage:
          type: integer
          default: 20
          maximum: 999
          description: ページ当たり項目数
      required:
        - result
        - total
        - currentPage
        - lastPage
        - perPage
    AirwayReservationCancellationResponse:
      type: object
      required:
        - airwayReservationId
        - operatorId
        - airwaySections
        - startAt
        - endAt
        - reservedAt
        - updatedAt
      properties:
        airwayReservationId:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: 航路予約ID
          example: '123e4567-e89b-12d3-a456-426614174000'
        operatorId:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: 運航事業者ID
          example: '123e4567-e89b-12d3-a456-426614174000'
        airwaySections:
          type: array
          minItems: 1
          maxItems: 99
          description: 航路区画予約情報
          items:
            type: object
            required:
              - airwaySectionId
              - startAt
              - endAt
            properties:
              airwaySectionId:
                type: string
                format: uuid
                minLength: 36
                maxLength: 36
                description: 航路区画ID
                example: '123e4567-e89b-12d3-a456-426614174000'
              startAt:
                type: string
                format: date-time
                description: 航路区画毎の予約開始日時
                example: '2025-01-13T09:00:00Z'
              endAt:
                type: string
                format: date-time
                description: 航路区画毎の予約終了日時
                example: '2025-01-13T16:00:00Z'
        status:
          type: string
          enum:
            - 'RESERVED'
            - 'CANCELED'
            - 'RESCINDED'
          description: 予約ステータス
          example: 'CANCELED'
        reservedAt:
          type: string
          format: date-time
          description: 予約完了日時
          example: '2024-12-13T18:53:38Z'
        updatedAt:
          type: string
          format: date-time
          description: 予約状態更新日時
          example: '2024-12-13T18:53:38Z'
    AirwayReservationRescissionResponse:
      type: object
      required:
        - airwayReservationId
        - operatorId
        - airwaySections
        - startAt
        - endAt
        - reservedAt
        - updatedAt
      properties:
        airwayReservationId:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: 航路予約ID
          example: '123e4567-e89b-12d3-a456-426614174000'
        operatorId:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: 運航事業者ID
          example: '123e4567-e89b-12d3-a456-426614174000'
        airwaySections:
          type: array
          minItems: 1
          maxItems: 99
          description: 航路区画予約情報
          items:
            type: object
            required:
              - airwaySectionId
              - startAt
              - endAt
            properties:
              airwaySectionId:
                type: string
                format: uuid
                minLength: 36
                maxLength: 36
                description: 航路区画ID
                example: '123e4567-e89b-12d3-a456-426614174000'
              startAt:
                type: string
                format: date-time
                description: 航路区画毎の予約開始日時
                example: '2025-01-13T09:00:00Z'
              endAt:
                type: string
                format: date-time
                description: 航路区画毎の予約終了日時
                example: '2025-01-13T16:00:00Z'
        status:
          type: string
          enum:
            - 'RESERVED'
            - 'CANCELED'
            - 'RESCINDED'
          description: 予約ステータス
          example: 'RESCINDED'
        reservedAt:
          type: string
          format: date-time
          description: 予約完了日時
          example: '2024-12-13T18:53:38Z'
        updatedAt:
          type: string
          format: date-time
          description: 予約状態更新日時
          example: '2024-12-13T18:53:38Z'
    Error400Response:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          required:
            - message
          properties:
            message:
              type: string
              example: 'BAD_REQUEST'
    Error404Response:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          required:
            - message
          properties:
            message:
              type: string
              example: 'NOT_FOUND'
    Error500Response:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          required:
            - message
          properties:
            message:
              type: string
              example: 'SERVER_ERROR'